name: Java CI
on:
  push:
    paths:
      - 'archetype-common/src/main/java/**.java'
      - 'archetype-common/pom.xml'
      - '.github/workflows/archetype-common.yml'
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          server-id: upload
      - run: |
          cd archetype-common
          mvn --batch-mode deploy -Drat.ignoreErrors=true
