name: Java CI
on:
  push:
    paths:
      - 'src/main/java/**.java' # - 'pom.xml' - '.github/workflows/build.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          server-id: upload # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots deploy -Drat.ignoreErrors=true
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES }}
